### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by cybr-coder** [anoshaahmed/nooki-website#1]
There is an error with the ruby image when the page is loaded
![image](https://user-images.githubusercontent.com/96119065/148130973-17dc2046-ffba-4306-ab36-227d65106d37.png)

**Comment by anoshaahmed** [comment]
Fixed it just now. I had written "Ruby.png" instead of "ruby.png" in src="". 
I didn't know it was case sensitive ! Thank you for opening this issue, this was fun lol :D
